### ISSUE TITLE
execute-on-startup.conf restoring to old version when server restarts

### ISSUE THREAD

**Issue by HackuJacku** [randombyte-developer/command-utils#16]
Whenever my server restarts, my execute-on-startup.conf keeps restoring to the following:

commands=[
    "say Server started!",
    rccratetimer,
    publictourneyrandoms,
    "rc randomraidbossselect",
    "world border set gyms 0 0 15000"
]

From:

commands=[
    "say Server started!",
    "rccratetimer",
    "publictourneyrandoms",
    "rc randomraidbossselect",
    "world border set gyms 0 0 15000"
]

**SpongeForge version:** 1.12.2-2838-7.2.2

**Comment by randombyte-developer** [comment]
That change doesn't invalidate the config. These changes are done by `configurate`, the Sponge config library. I don't have control over that.
But in the end it doesn't matter, since the config is still valid. `configurate` apparantly does this to strings/commands that don't contain spaces. This is documented in the [HOCON specification](https://github.com/lightbend/config/blob/master/HOCON.md#unquoted-strings).

Do you experience any negative impact from these automatic changes?
